#!/bin/bash
set -o errexit

HISTORY="$HOME/.local/src/dmenu/.drun_history"
test -f "$HISTORY" || touch "$HISTORY"
INPUT=$(dmenu $@ < "$HISTORY")
test -n "$INPUT"

# aliases
case "$INPUT" in
    google)
        CMD="xdg-open http://google.com" ;;
    vnote)
        CMD="$TERMINAL -e vnote" ;;
    lf)
        CMD="$TERMINAL -e lfub" ;;
    grub-customizer)
        CMD="sudo grub-customizer" ;;
    multibootusb)
        CMD="sudo multibootusb" ;;
    pass)
        CMD="$TERMINAL -e pass.sh" ;;
    cron)
        CMD="$TERMINAL -e $EDITOR /var/spool/cron/kalex && crontog && sleep 2; crontog" ;;
        #CMD="sudo systemctl reload cronie.service"
    syncGitHub)
        CMD="syncDots.sh" ;;
        #CMD="sudo systemctl reload cronie.service"
    *)
        CMD="$INPUT" ;;
esac

# test if CMD exist in $PATH
hash $(echo "$CMD" | cut -f1 -d ' ')

# write input to history
if ! grep -q "$INPUT" "$HISTORY"; then
    echo "$INPUT" >> "$HISTORY"
    sort "$HISTORY" -o "$HISTORY" &
fi

exec $CMD
